### ISSUE TITLE
NEED to LIST dependencies and how to install them

### ISSUE THREAD

**Issue by NotAsea** [cnfatal/rpycdec#1]
while trying this package, currently this cannot run due to lack of plyvel, which is pain in the ass to build in window, I suggest you explicitly list what dependencies of your project, or packaging together when release.
If you interest here is what happend when install in python 3.12
```bash
 > py -m rpycdec
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\phan mem lung tung\Scoop\apps\python\3.12.0\Lib\site-packages\rpycdec.py", line 20, in <module>
    import plyvel
ModuleNotFoundError: No module named 'plyvel'
```

**Comment by NotAsea** [comment]
anyway try install this in python 3.9 which has playvel-win32 support and another error:
```bash
Traceback (most recent call last):
  File "D:\phan mem lung tung\Scoop\apps\python39\3.9.13\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\phan mem lung tung\Scoop\apps\python39\3.9.13\lib\runpy.py", line 158, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\phan mem lung tung\Scoop\apps\python39\3.9.13\lib\site-packages\rpycdec.py", line 147
    match char:
          ^
SyntaxError: invalid syntax
```
ah yesh and inside pyproj you proudly write require python > 3.7 but use feature in python 3.10 which no backward compatible, bruh

**Comment by cnfatal** [comment]
Hi, i'm using sqlite3 instead of plyvel for cache inorder to support windows, please try  again.

feedback are welcome  if there are any questions.
