### ISSUE TITLE
NotImplementedError №1

### ISSUE THREAD

**Issue by D0n-A** [cnfatal/rpycdec#5]
Good afternoon!

My configuration is as follows:

1. Windows 11 23H3;
2. Python 3.11.7;
3. RPYC was compiled on RenPy 7.4.11.2266.

When trying to decode the test.rpyc file, the following error is returned:

```
D:\233>rpycdec D:\233
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Scripts\rpycdec.exe\__main__.py", line 7, in <module>
  File "C:\Python\Lib\site-packages\rpycdec.py", line 677, in main
    decompile(args.src[0], args.dest)
  File "C:\Python\Lib\site-packages\rpycdec.py", line 578, in decompile
    decompile_file(
  File "C:\Python\Lib\site-packages\rpycdec.py", line 556, in decompile_file
    code = renpy.util.get_code(stmts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\renpy\util.py", line 102, in get_code
    rv.append(get_code(item, **kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\renpy\util.py", line 109, in get_code
    return node.get_code(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\renpy\ast.py", line 714, in get_code
    raise NotImplementedError
NotImplementedError
```

Decompilation by other utilities (for example, UnRen mastermod by Gideon v.10) is successful, but for some reason there are no comments in the code.

And here's and rpyc itself:
[test.rpyc.txt](https://github.com/cnfatal/rpycdec/files/15267012/test.rpyc.txt)

Thank you in advance!

**Comment by D0n-A** [comment]
This file has been successfully unpacked too. Thank you very much again!
